### ISSUE TITLE
[Typo]: Change the text of home page "Add a items" to "Add items"

### ISSUE THREAD

**Issue by ritikkumargithub** [ritikkumargithub/todolist#1]
** I want to change the text of Home page from  "Add a items" to "Add items" **

** Image of home page **
![Screenshot 2023-11-20 223257](https://github.com/ritikkumargithub/todolist/assets/89859408/c42b9913-338c-4f46-ab1d-d407255ba139)

**Comment by Nasirahamad88** [comment]
I am working
